# !This file must be setup before using this plugin!
# Once a feature is enabled, disabling it again may result in undefined behavior
# If you really want to disable a feature, but this wrecks your whitelist/install, you should delete the data.yml file

# See https://modrinth.com/plugin/discordio on how to get a token
botToken:   "Insert your token here, see the https://modrinth.com/plugin/discordio on how to get a token"
# Guild ID is needed for adding commands
guildId:    "Insert your guild id here (the ID of your discord server)"

# Discord messages for in game events
events:
  # On server start message
  onStart:
    enabled: false
    disableDuringMaintenance: true
    channel: "id..."

  # On server stop message
  onStop:
    enabled: false
    disableDuringMaintenance: true
    channel: "id..."

  # On player join message
  onJoin:
    enabled: false
    disableDuringMaintenance: true
    channel: "id..."

  # On player leave message
  onLeave:
    enabled: false
    disableDuringMaintenance: true
    channel: "id..."

  # On discord/minecraft message forward it
  onMessage:
    enabled: false
    disableDuringMaintenance: true

    # Forward minecraft messages to discord
    minecraftToDiscord: true
    # Forward discord messages to minecraft
    discordToMinecraft: true

    # Uncomment the one that applies to your server type:

    # For fabric:
    # channels:
    #   fabric: "id..."

    # For velocity
    # (The server names are the ones specified in the velocity.toml file you configured)
    # Do not share discord channels if you have discordToMinecraft enabled
    # channels:
    #   server1: "id..."
    #   server2: "id..."


# If enabled, will use the UUID registered at mojang for verification
# !The server must be in online mode to use this!
# You currently cannot change this setting after you have someone whitelisted, so choose carefully
# If you really want to change this, delete the data.yml file (this will remove all whitelisted players, they will need to be whitelisted again)
useUUID: true
# If enabled only one minecraft account is allowed per discord user
# You currently cannot change this setting after you have someone whitelisted, so choose carefully
# If you really want to change this, delete the data.yml file (this will remove all whitelisted players, they will need to be whitelisted again)
connectAccounts: true

# If set to false, this plugin will delete all the interactable messages on shutdown, to then resend them on startup
# If set to true, this plugin will disable all the interactable messages on shutdown, to then enable them again on startup (so no annoying ping when the server starts up)
disableOnShutdown: true

# Combine the whitelist, ban and unban request message in one single request message
squashedRequest:
  enabled: false
  channel: "id..."

# Whitelisting via discord
whitelist:
  enabled: false

  # Should this plugin give someone that is whitelisted a special role
  giveRoleOnWhitelist: false
  # The role to give a player when he is whitelisted (only if giveRoleOnWhitelist=true)
  # Enable developer options to get the role ID easily from the discord server settings:
  whitelistedRoleID: ""

  onAccept:
    enabled: true
    channel: "id..."
  onDeny:
    enabled: true
    channel: "id..."
  request:
    enabled: true
    channel: "id..."
    checkRoles: false
    allowedRoles: []
  voting:
    # If disabled, a request will imply immediate whitelist
    enabled: true
    channel: "id.."
    checkRoles: false
    allowedRoles: []
    acceptVotes: "50%"
    denyVotes: "1"

# Banning via discord
banning:
  enabled: false

  # Should this plugin give someone that is banned a special role
  giveRoleOnBan: false
  # The role to give a player when he is banned (only if giveRoleOnBan=true)
  # Enable developer options to get the role ID easily from the discord server settings:
  bannedRoleID: ""

  onAccept:
    enabled: true
    channel: "id..."
  onDeny:
    enabled: true
    channel: "id..."
  request:
    enabled: true
    channel: "id..."
    checkRoles: false
    allowedRoles: []
    # Choose one of the following ways a user can choose who he wants to ban:
    # - "discord" select the discord username they want banned (cannot be used if connectAccounts=false)
    # - "minecraft" select the minecraft username they want banned
    identifier: "discord"
  punishment:
    # If disabled, a request will proceed as a perm ban request to reason picking
    enabled: true
    channel: "id..."
    checkRoles: false
    allowedRoles: []
    acceptVotes: "50%"
    denyVotes: "1"
    punishments:
      # If you do not keep the none punishment, the admins cannot deny a ban request
      "None":
        type: None
      "Permanent ban":
        type: PermBan
      "5m ban":
        type: Ban
        duration: 300
      "1h ban":
        type: Ban
        duration: 3600
      "2h ban":
        type: Ban
        duration: 7200
      "1d ban":
        type: Ban
        duration: 86400
      "kick 1x":
        type: Kick
        duration: 1
      "kick 3x":
        type: Kick
        duration: 3
      "No unban 2h":
        type: NoUnban
        duration: 7200
  reason:
    # If disabled, a request will keep the reason of the request
    enabled: true
    channel: "id..."
    checkRoles: false
    allowedRoles: []
    acceptVotes: "50%"
    denyVotes: "1"

# Unbanning via discord
unban:
  enabled: false

  onAccept:
    enabled: true
    channel: "id..."
  onDeny:
    enabled: true
    channel: "id..."
  request:
    enabled: true
    channel: "id..."
    checkRoles: false
    allowedRoles: []
  voting:
    # If disabled, a request will imply immediate unban
    enabled: true
    channel: "id.."
    checkRoles: false
    allowedRoles: []
    acceptVotes: "50%"
    denyVotes: "1"

maintenance:
  # Disables events and rejects everyone not on the crew list
  enabled: false
  # Enable maintenance mode from the config:
  inMaintenance: false
  # Players allowed to join during maintenance
  # Use UUID's if useUUID=true, else use player names
  # This does not override the whitelist and banning features, you still need to be whitelisted to enter
  # A UUID should be without dashes so: 123456789abcdefghijklmni12345678
  crew: ["player1", "player2"]
  # Command to enable maintenance mode via discord
  command:
    enabled: false
    checkChannel: false
    allowedChannels: ["id..."]
    checkRoles: false
    allowedRoles: []
  # On start messages
  onStart:
    enabled: false
    channel: "id..."
  # On end message
  onStop:
    enabled: false
    channel: "id..."

# A discord command to see if someone is whitelisted or not (and if the person has punishments)
infoCommand:
  enabled: false
  checkChannel: false
  allowedChannels: ["id..."]
  checkRoles: false
  allowedRoles: []